import React from 'react';
import {AbsoluteFill, Composition, Sequence, interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion';

const C={paper:'#F4EBE1',blue:'#E3EEF8',pink:'#FCEAE6',mint:'#E3F1E8',ink:'#171717',grey:'#B9B6B0',orange:'#E9C9A8'};
const font='Arial, "PingFang SC", "Microsoft YaHei", sans-serif';
const clamp=(x:number,a=0,b=1)=>Math.max(a,Math.min(b,x));
const fade=(f:number,s:number,e:number)=>interpolate(f,[s,e],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const pop=(f:number,s:number)=>spring({frame:Math.max(0,f-s),fps:30,config:{damping:16,stiffness:120}});
function Box({children,style={}}:{children:React.ReactNode;style?:React.CSSProperties}){return <div style={{border:`0.8px solid ${C.ink}`,boxSizing:'border-box',...style}}>{children}</div>}
function Phone({f}:{f:number}){const y=interpolate(f,[0,35,85,105],[80,0,0,-70],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <div style={{transform:`translateY(${y}px) rotate(-7deg)`,opacity:fade(f,0,12),position:'absolute',left:'16%',bottom:'12%',width:250,height:465,borderRadius:30,background:C.orange,border:`0.8px solid ${C.ink}`,padding:20,boxShadow:'12px 12px 0 #D6C6B5'}}><div style={{height:'100%',borderRadius:18,background:C.ink,padding:10}}><div style={{height:'100%',borderRadius:12,background:C.blue,position:'relative',overflow:'hidden'}}><div style={{fontSize:13,padding:14}}>NOKIA</div><div style={{position:'absolute',top:'35%',left:20,right:20,height:100,background:C.paper,border:`0.8px solid ${C.ink}`,padding:12,fontSize:17}}>你还记得<br/>你的第一部手机<br/>用的什么系统吗？</div><div style={{position:'absolute',bottom:18,left:20,right:20,display:'flex',justifyContent:'space-between',fontSize:22}}>◀　⌕　▶</div></div></div></div>}
function Scene1(){const f=useCurrentFrame();return <AbsoluteFill style={{background:C.paper,fontFamily:font,color:C.ink}}><div style={{padding:55,fontSize:22,letterSpacing:2}}>MOBILE OS EXTINCTION / 01</div><div style={{position:'absolute',left:'50%',top:'32%',fontSize:58,lineHeight:1.25,opacity:fade(f,12,30)}}>一部手机，<br/><span style={{background:C.pink,padding:'0 12px'}}>一个时代。</span></div><Phone f={f}/><div style={{position:'absolute',right:'10%',bottom:'13%',fontSize:18,opacity:fade(f,55,80)}}>后来，系统开始消失。</div></AbsoluteFill>}
const os=[['SYMBIAN',C.mint,'◉'],['WINDOWS PHONE',C.blue,'▦'],['BLACKBERRY',C.pink,'⌨'],['webOS',C.orange,'▰']];
function Popup({item,i,f}:{item:string[];i:number;f:number}){const x=[8,34,58,25][i], y=[20,12,35,58][i]; const q=pop(f, i*12+4);return <Box style={{position:'absolute',left:`${x}%`,top:`${y}%`,width:240,height:130,background:item[1],padding:18,transform:`translateY(${(1-q)*35}px) rotate(${[-4,3,-2,4][i]}deg)`,opacity:q,boxShadow:'7px 7px 0 rgba(23,23,23,.12)'}}><div style={{fontSize:28}}>{item[2]}</div><div style={{fontWeight:700,marginTop:8}}>{item[0]}</div><div style={{fontSize:12,marginTop:10}}>系统未响应 · 2010—2016</div></Box>}
function Scene2(){const f=useCurrentFrame();return <AbsoluteFill style={{background:C.blue,fontFamily:font,color:C.ink}}><div style={{padding:55,fontSize:22}}>02 / POPUPS FROM THE PAST</div>{os.map((x,i)=><Popup key={i} item={x} i={i} f={f}/>)}<div style={{position:'absolute',bottom:48,left:55,fontSize:30,opacity:fade(f,70,90)}}>它们不是被升级淘汰的。<br/><b>它们是直接消失的。</b></div></AbsoluteFill>}
function Pillar({name,color,x,h,delay,f}:{name:string;color:string;x:number;h:number;delay:number;f:number}){const q=pop(f,delay);return <div style={{position:'absolute',bottom:80,left:`${x}%`,width:230,height:h,background:color,border:`0.8px solid ${C.ink}`,transform:`scaleY(${q})`,transformOrigin:'bottom',display:'flex',alignItems:'center',justifyContent:'center',fontSize:32,fontWeight:700}}>{name}</div>}
function Scene3(){const f=useCurrentFrame();return <AbsoluteFill style={{background:C.paper,fontFamily:font,color:C.ink}}><div style={{padding:55,fontSize:22}}>03 / TWO PILLARS</div><div style={{position:'absolute',top:'22%',left:'50%',transform:'translateX(-50%)',fontSize:48,opacity:fade(f,0,20)}}>最后，只剩下两个答案。</div><Pillar name="iOS" color={C.pink} x={24} h={470} delay={18} f={f}/><Pillar name="Android" color={C.mint} x={60} h={560} delay={30} f={f}/><div style={{position:'absolute',bottom:32,left:55,fontSize:16}}>封闭的花园　　开放的大陆</div></AbsoluteFill>}
function Scene4(){const f=useCurrentFrame();const g=interpolate(f,[0,45,90],[1,1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <AbsoluteFill style={{background:`rgb(${Math.round(244*g+185*(1-g))},${Math.round(235*g+183*(1-g))},${Math.round(225*g+180*(1-g))})`,fontFamily:font,color:C.ink}}><div style={{padding:55,fontSize:22,opacity:g}}>04 / EXTINCTION</div><div style={{position:'absolute',inset:0,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',opacity:g}}><div style={{fontSize:88,fontWeight:700,letterSpacing:8}}>0%</div><div style={{fontSize:24,marginTop:20}}>市场份额</div><div style={{width:620,height:1,background:C.ink,marginTop:40,transform:`scaleX(${clamp(1-f/70)})`}}/><div style={{fontSize:34,marginTop:45}}>然后，全没了。</div></div></AbsoluteFill>}
export function MobileOSExtinction(){return <AbsoluteFill style={{background:C.paper}}><Sequence from={0} durationInFrames={120}><Scene1/></Sequence><Sequence from={120} durationInFrames={120}><Scene2/></Sequence><Sequence from={240} durationInFrames={120}><Scene3/></Sequence><Sequence from={360} durationInFrames={120}><Scene4/></Sequence></AbsoluteFill>}
export const RemotionRoot=()=> <Composition id="MobileOSExtinction" component={MobileOSExtinction} durationInFrames={480} fps={30} width={1920} height={1080} />;